"""
Django settings for matcherapp project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

import environ

env = environ.Env()
SECRET_KEY = env(
    "SECRET_KEY"
)  # 'django-insecure-h!szw@=fc-m@4*s!hg@l(92of@in1p@4-8pc@0f31ugps=r#j#'

ALLOWED_HOSTS = env("ALLOWED_HOSTS").split(",")
CORS_ALLOWED_ORIGINS = env("CORS_ALLOWED_ORIGINS").split(",")

BASE_DIR = Path(__file__).resolve().parent.parent
# SECURE_SSL_REDIRECT = env("SECURE_SSL_REDIRECT")

DJANGO_SU_EMAIL = env("DJANGO_SU_EMAIL")
DJANGO_SU_PASSWORD = env("DJANGO_SU_PASSWORD")
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "simple_history",
    "drf_yasg",
    "corsheaders",
    "ebhealthcheck.apps.EBHealthCheckConfig",
    "django_q",
    "health_check",
    "health_check.db",
    "testscheduler",
    "form2metrics",
    "mailing",
    "import_export",
    "djangoqadmin"
]
IMPORT_EXPORT_USE_TRANSACTIONS = True


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "matcherapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "matcherapp.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
REST_FRAMEWORK = {"DEFAULT_AUTHENTICATION_CLASSES": []}

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Basic": {"type": "basic"},
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"},
    }
}

#
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "console": {"format": "%(name)-12s %(levelname)-8s %(message)s"},
#         "file": {"format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"},
#     },
#     "handlers": {
#         "console": {"class": "logging.StreamHandler", "formatter": "console"},
#         "file": {
#             "level": "DEBUG",
#             "class": "logging.FileHandler",
#             "formatter": "file",
#             "filename": "/tmp/debug.log",
#         },
#     },
#     "loggers": {"": {"level": "DEBUG", "handlers": ["console", "file"]}},
# }

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
#
# LANGUAGE_CODE = env("LANGUAGE_CODE") #'en-us'
#
# TIME_ZONE =  env("TIME_ZONE") #'UTC'
#
# USE_I18N = env("USE_I18N")
#
# USE_TZ =env("USE_TZ")# True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000"
]

Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 4,
    'timeout': 90,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default'
}